version: '3.4'

services:

  pixel-test-runner:
    image: {0}
    networks:
     - pixel-network
    entrypoint: ["dotnet", "pixel-run.dll", "run", "template", {1}]

networks:
  pixel-network:
    external: true
