name: Publish pixel-persistence service to docker hub on tag push to main

on:
  workflow_dispatch:
  push:    
    tags:        
      - v*

jobs:

  build-and-publish-to-docker-hub:
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:     
    - name: Checkout Repository
      uses: actions/checkout@v3  
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/pixel-persistence
    - name: Build docker image locally
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./src/Pixel.Persistence.Services.Api/Dockerfile        
          push: false
          tags: pixel-persistence:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true  
    - name: Login to docker hub      
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to docker hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pixel-persistence:${{ github.ref_name }}