name: Publish pixel-run to docker hub on tag push to main

on:
  workflow_dispatch:
  push:    
    tags:        
      - v*

jobs:

  build-and-publish-to-docker-hub:
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:     

    - name: Checkout Repository
      uses: actions/checkout@v4  

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/pixel-run
        labels: |
            org.opencontainers.image.title=pixel-run
            org.opencontainers.image.description=Test runner for pixel-automation

    - name: Login to docker hub      
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image locally
      uses: docker/build-push-action@v5
      with:
          context: ./
          file: ./src/Pixel.Persistence.Automation.Test.Runner/Dockerfile        
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true  