name: Build for windows

on: [workflow_call]

jobs:
  build-for-windows:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [windows-latest]
       dotnet-version: [ '6.0.x' ]    
    steps:     
    - name: Restore dependencies for pixel-designer
      run: dotnet restore src/Pixel.Automation.Designer.Views/Pixel.Automation.Designer.Views.csproj

    - name: Build pixel-designer for runtime win10-64 and targetframework net6.0-windows
      run: dotnet build src/Pixel.Automation.Designer.Views/Pixel.Automation.Designer.Views.csproj -c release --no-restore --runtime win10-x64 --self-contained false -p:TargetFramework=net6.0-windows

    - name: Restore dependencies for pixel-runner
      run: dotnet restore src/Pixel.Automation.Test.Runner/Pixel.Automation.Test.Runner.csproj

    - name: Build pixel-runner for runtime win10-64 and targetframework net6.0-windows
      run: dotnet build src/Pixel.Automation.Test.Runner/Pixel.Automation.Test.Runner.csproj -c release --no-restore --runtime win10-x64 --self-contained false -p:TargetFramework=net6.0-windows
    
    - name: Restore dependencies for pixel-persistence
      run: dotnet restore src/Pixel.Persistence.Services.Api/Pixel.Persistence.Services.Api.csproj

    - name: Publish pixel-persistence for runtime win10-x64
      run: dotnet publish src/Pixel.Persistence.Services.Api/Pixel.Persistence.Services.Api.csproj -c Release --no-restore --runtime win10-x64 --self-contained false -o .builds/Release/Service

    - name: Upload pixel-designer artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pixel-designer-${{ matrix.os }}
        path: .builds/Release/Designer/win10-x64
    
    - name: Upload pixel-runner artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pixel-runner-${{ matrix.os }}
        path: .builds/Release/Runner/win10-x64  
    
    - name: Upload pixel-persistence artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pixel-persistence-${{ matrix.os }}
        path: .builds/Release/Service/win10-x64   